version: "2.1"
services:

  rsyslog:
    image: rsyslog/syslog_appliance_alpine
    ports: 
      - '513:514'
      - '1601:1601'
      - '6514:6514'
    environment:
      - RSYSLOG_CONF=/config/rsyslog.conf
    volumes:
      - ./rsyslog/log:/log
      - ./rsyslog/work:/work
      - ./rsyslog/config:/config

  influxdb:
    image: influxdb
    ports: 
      - '8086:8086'
    env_file:
      - ./.environment.env
    volumes:
        - '$pwd/influxdb:/var/lib/influxdb'

  telegraf:
    image: telegraf
    command:
      - '--config.file=/telegraf/telegraf.conf'
    ports: 
      - '8092:8092'
      - '8094:8094'
      - '8125:8125'
    volumes: 
      - './telegraf/telegraf.conf:/telegraf/telegraf.conf'

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    #volumes:
    #  - ./grafana:/etc/grafana/
    env_file:
      - ./.environment.env